# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidexflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidex
  template:
    metadata:
      labels:
        app: bidex
    spec:
      containers:
      - name: bidexflask1
        # Replace $GCLOUD_PROJECT with your project ID
        image: us-east1-docker.pkg.dev/bidex-atl/bidex-repo/bidex-flask:ver14

        #gcr.io/beam-personals/bidexflask1:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
 