apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: bidex-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidex-redis
  template:
    metadata:
      labels:
        app: bidex-redis
    spec:
      containers:
      - name: redis
        image: "docker.io/redis:6.0.5"
        ports:
        - containerPort: 6379